//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pekarnia.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.ElementGoods = new HashSet<ElementGoods>();
        }
    
        public int idGoods { get; set; }
        public string Name { get; set; }
        public double Quantity { get; set; }
        public int idUnit { get; set; }
        public decimal Price { get; set; }
        public int idUnitMoney { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementGoods> ElementGoods { get; set; }
        public virtual UnitMoney UnitMoney { get; set; }
        public virtual Units Units { get; set; }
    }
}
